(function(){
var bank=window.QBANK||[],errors=[],choiceOK=0,totalChoices=0;
function hasStatus(s){return /^【(正しい|誤り)】/.test(String(s||''));}
function substantive(s){s=String(s||'');return s.length>=70&&(s.indexOf('【関連知識】')>=0||s.indexOf('【原理')>=0||s.indexOf('【試験')>=0||s.length>=120);}
bank.forEach(function(x){if(!x||!Array.isArray(x.e))return;x.e.forEach(function(s,i){totalChoices++;if(hasStatus(s)&&substantive(s))choiceOK++;else errors.push(x.id+'-'+(i+1)+':詳細解説基準不足');});});
function get(id){return bank.find(function(x){return x.id===id});}
var rxExpected=['T03','T04','H04','H07','T08','T11','H09','T14'];rxExpected.forEach(function(id){var x=get(id);if(!x||!Array.isArray(x.rxn)||!x.rxn.length)errors.push(id+':反応式付加漏れ');});
var termExpected=['G01','G03','G04','W05','W07','T03','T04','T05','T07','H01','H04','H05','H06','H07','L03','L05','G08','G10','W08','W09','W10','T09','T10','T11','H08','H09','H10','L08','L09','L10','G11','G13','W11','W12','W13','T12','T13','T14','H11','H12','H13','L11','L12','G14','G15','G16','W14','W15','W16','T15','T16','T17','H14','H15','H16','L14','L15','L16'];termExpected.forEach(function(id){var x=get(id);if(!x||!Array.isArray(x.terms)||!x.terms.length)errors.push(id+':用語ミニ解説付加漏れ');});
var preVisual=['G06','W06','T06','H06','L06','T08'];preVisual.forEach(function(id){var x=get(id);if(!x||!x.v)errors.push(id+':問題用図表付加漏れ');});
var postVisual=['G04','W05'];postVisual.forEach(function(id){var x=get(id);if(!x||!x.av)errors.push(id+':解説補助グラフ付加漏れ');});
var ids={};bank.forEach(function(x){if(ids[x.id])errors.push(x.id+':ID重複');ids[x.id]=1;if(!Array.isArray(x.o)||x.o.length!==5)errors.push(x.id+':5肢不備');if(!Number.isInteger(x.a)||x.a<0||x.a>4)errors.push(x.id+':正答番号不正');if(Array.isArray(x.o)&&new Set(x.o).size!==5)errors.push(x.id+':選択肢重複');if(Array.isArray(x.e)&&new Set(x.e).size!==5)errors.push(x.id+':解説重複');});
window.WATER1_QUALITY_AUDIT={questions:bank.length,totalChoices:totalChoices,choiceOK:choiceOK,errors:errors.slice(),reactionOK:rxExpected.filter(function(id){var x=get(id);return x&&x.rxn&&x.rxn.length}).length,reactionExpected:rxExpected.length,termOK:termExpected.filter(function(id){var x=get(id);return x&&x.terms&&x.terms.length}).length,termExpected:termExpected.length,visualOK:preVisual.filter(function(id){var x=get(id);return x&&x.v}).length+postVisual.filter(function(id){var x=get(id);return x&&x.av}).length,visualExpected:preVisual.length+postVisual.length};
function msg(){var a=window.WATER1_QUALITY_AUDIT;return ' ｜ 詳細解説監査：'+a.choiceOK+'/'+a.totalChoices+'肢 '+(a.choiceOK===a.totalChoices?'合格':'要確認')+' ｜ 反応式 '+a.reactionOK+'/'+a.reactionExpected+' ｜ 用語 '+a.termOK+'/'+a.termExpected+' ｜ 図表 '+a.visualOK+'/'+a.visualExpected;}
var painting=false;function paint(){var el=document.getElementById('audit');if(!el||painting)return;painting=true;var base=(el.textContent||'').split(' ｜ 詳細解説監査：')[0];el.textContent=base+msg();painting=false;if(errors.length){var w=document.getElementById('warn');if(w&&!document.getElementById('qualityWarn')){var d=document.createElement('div');d.className='warn';d.id='qualityWarn';d.innerHTML='<b>v7品質監査：</b><br>'+errors.join('<br>');w.appendChild(d);}}}
function install(){paint();var el=document.getElementById('audit');if(el)new MutationObserver(function(){paint();}).observe(el,{childList:true,characterData:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0)});else setTimeout(install,0);
})();