const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const scripts=['qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js','qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_gap_batch10_v7.js','qbank_gap_batch11_v7.js','qbank_gap_batch12_v7.js','qbank_detail_quality_fix_v23.js','qbank_undefined_fix_v7.js'];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],body:{},createElement:()=>({})};
const store=new Map();const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage,Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=localStorage;vm.createContext(ctx);
for(const f of scripts){const p=path.join(root,f);if(!fs.existsSync(p))throw new Error('missing '+f);vm.runInContext(fs.readFileSync(p,'utf8'),ctx,{filename:f});}
vm.runInContext(fs.readFileSync(path.join(root,'qbank_quality_audit_v7.js'),'utf8'),ctx,{filename:'qbank_quality_audit_v7.js'});
const bank=ctx.window.QBANK,qa=ctx.window.WATER1_QUALITY_AUDIT,errs=[];const ok=(c,m)=>{if(!c)errs.push(m)};
ok(bank.length===200,`question count ${bank.length}`);ok(qa&&qa.totalChoices===1000,`choice audit ${qa&&qa.totalChoices}`);ok(qa&&qa.choiceOK===1000,`detail ${qa&&qa.choiceOK}/1000 ${(qa&&qa.errors||[]).join('; ')}`);ok(qa&&qa.reactionOK===23&&qa.reactionExpected===23,`reactions ${qa&&qa.reactionOK}/${qa&&qa.reactionExpected}`);ok(qa&&qa.visualOK===23&&qa.visualExpected===23,`visuals ${qa&&qa.visualOK}/${qa&&qa.visualExpected}`);
let choices=0,termQ=0,problemVisuals=0,undefinedCount=0;const ids=new Set();for(const x of bank){ok(!ids.has(x.id),`duplicate id ${x.id}`);ids.add(x.id);ok(Array.isArray(x.o)&&x.o.length===5,`${x.id} choices`);ok(Array.isArray(x.e)&&x.e.length===5,`${x.id} explanations`);ok(Number.isInteger(x.a)&&x.a>=0&&x.a<5,`${x.id} answer`);if(Array.isArray(x.o)){choices+=x.o.length;ok(new Set(x.o).size===5,`${x.id} duplicate choice`)}if(Array.isArray(x.e)){ok(new Set(x.e).size===5,`${x.id} duplicate explanation`);ok(x.e.every(e=>/^【(正しい|誤り)】/.test(String(e||''))),`${x.id} status labels`);ok(x.e.every(e=>String(e||'').length>=70),`${x.id} explanation length`);x.e.forEach((e,i)=>{if(/\bundefined\b/.test(String(e||''))){undefinedCount++;ok(false,`${x.id}.e${i+1} literal undefined`)}})}if(Array.isArray(x.terms)&&x.terms.length)termQ++;if(x.v)problemVisuals++;}
ok(choices===1000,`choice count ${choices}`);ok(undefinedCount===0,`undefined explanations ${undefinedCount}`);ok(termQ>=174,`terms questions ${termQ}`);ok(problemVisuals>=20&&problemVisuals<=40,`problem visual ratio ${problemVisuals}/200`);
const get=id=>bank.find(x=>x.id===id),batch12=['G38','G39','W38','W39','T43','T44','H39','H40','L38'];for(const id of batch12){const x=get(id);ok(!!x,`${id} missing`);if(x){ok(x.detailGrade==='v7-full',`${id} detailGrade`);ok(Array.isArray(x.terms)&&x.terms.length,`${id} terms`);}}
for(const id of ['G38','W39','H39','L38'])ok(get(id)&&get(id).v,`${id} visual`);for(const id of ['H40','L38'])ok(get(id)&&Array.isArray(get(id).rxn)&&get(id).rxn.length,`${id} reaction`);
ok(get('G38')&&get('G38').a===1&&/42\.1%/.test(get('G38').p)&&/54\.7%/.test(get('G38').p),'G38 industrial waste stats');ok(get('G39')&&get('G39').a===3&&/PCDD/.test(get('G39').p)&&/PCDF/.test(get('G39').p)&&/コプラナーPCB/.test(get('G39').p)&&/TEQ/.test(get('G39').p),'G39 dioxin TEQ');ok(get('W38')&&get('W38').a===2&&/第一種特定化学物質/.test(get('W38').p)&&/指定物質/.test(get('W38').p),'W38 law classification');ok(get('W39')&&get('W39').a===1&&/4\.0/.test(get('W39').p)&&/3\.0/.test(get('W39').p)&&/2\.0/.test(get('W39').p),'W39 bottom DO');ok(get('T43')&&get('T43').a===4&&/溶存無機態窒素だけではなく/.test(get('T43').p),'T43 total nitrogen');ok(get('T44')&&get('T44').a===2&&/熱収支/.test(get('T44').p),'T44 sludge dewatering incineration');ok(get('H39')&&get('H39').a===1&&/70%/.test(get('H39').p)&&/標準添加法/.test(get('H39').p),'H39 recovery');ok(get('H40')&&get('H40').a===3&&/AsH3/.test(get('H40').p)&&/気液分離/.test(get('H40').p),'H40 arsenic hydride');ok(get('L38')&&get('L38').a===2&&/系統分離/.test(get('L38').p)&&/HCN/.test(get('L38').p),'L38 plating flow');
const subj={};for(const x of bank)subj[x.s]=(subj[x.s]||0)+1;ok(subj['公害総論']===39,`G ${subj['公害総論']}`);ok(subj['水質概論']===39,`W ${subj['水質概論']}`);ok(subj['汚水処理特論']===44,`T ${subj['汚水処理特論']}`);ok(subj['水質有害物質特論']===40,`H ${subj['水質有害物質特論']}`);ok(subj['大規模水質特論']===38,`L ${subj['大規模水質特論']}`);
const loader=fs.readFileSync(path.join(root,'qbank_patch_v5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),reg=fs.readFileSync(path.join(root,'qbank_regression_audit_v14.js'),'utf8'),quality=fs.readFileSync(path.join(root,'qbank_quality_audit_v7.js'),'utf8'),chem=fs.readFileSync(path.join(root,'qbank_chem_v7.js'),'utf8');
ok(loader.includes('qbank_gap_batch12_v7.js?v=124')&&loader.includes('qbank_undefined_fix_v7.js?v=124')&&loader.includes('qbank_chem_v7.js?v=124'),'loader release v124');ok(sw.includes('qbank_undefined_fix_v7.js'),'service worker explanation cleanup');ok(sw.includes('final200-ui-chem-audit'),'service worker chemistry audit cache');ok(/if\(el\.textContent!==next\)el\.textContent=next/.test(quality),'quality observer is idempotent');ok(!chem.includes("'@@SUP'+holds.length+'@@'"),'unsafe chemical placeholder removed');ok(chem.includes("'§§['+holds.length+']§§"),'safe chemical placeholder present');ok(chem.includes("replace(/SeH2/g,'H2Se')"),'selenium hydride correction present');ok(/var KEY='water1_bank_v3'/.test(index),'history key preserved');ok(/function save\(\)\{try\{localStorage\.setItem/.test(index),'instant save function');ok(/\.ch\.good\{[^}]*#16a34a/.test(index),'green answer CSS');ok(/\.ch\.bad\{[^}]*#dc2626/.test(index),'red answer CSS');ok(/次の問題へ/.test(index),'next UI');ok(/全5肢の解説を開く/.test(index),'all-choice explanation UI');ok(/問題数200/.test(reg)&&/1000肢/.test(reg)&&/第12弾9問/.test(reg),'browser regression final200');
localStorage.setItem('probe','ok');ok(localStorage.getItem('probe')==='ok','localStorage probe');localStorage.removeItem('probe');console.log('BANK',bank.length,'CHOICES',choices,'QUALITY',`${qa.choiceOK}/${qa.totalChoices}`,'UNDEFINED',undefinedCount,'TERMS',termQ,'RX',`${qa.reactionOK}/${qa.reactionExpected}`,'VIS',`${qa.visualOK}/${qa.visualExpected}`,'PROBLEM_VISUALS',problemVisuals,'SUBJECTS',JSON.stringify(subj));console.log('BATCH12',batch12.map(id=>`${id}:${get(id).t}`).join(' | '));if(errs.length){console.error('FAIL\n'+errs.join('\n'));process.exit(1)}console.log('PASS Batch12 final200 static quality/UI regression audit');