const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const scripts=['qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js','qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_detail_quality_fix_v23.js'];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],body:{},createElement:()=>({})};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage:{getItem:()=>null,setItem:noop,removeItem:noop},Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=ctx.localStorage;vm.createContext(ctx);
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
vm.runInContext(fs.readFileSync(path.join(root,'qbank_quality_audit_v7.js'),'utf8'),ctx,{filename:'qbank_quality_audit_v7.js'});
const bank=ctx.window.QBANK,qa=ctx.window.WATER1_QUALITY_AUDIT;const errs=[];const ok=(cond,msg)=>{if(!cond)errs.push(msg)};
ok(bank.length===171,`question count ${bank.length}`);ok(qa&&qa.totalChoices===855,`quality choices ${qa&&qa.totalChoices}`);ok(qa&&qa.choiceOK===855,`production detail ${qa&&qa.choiceOK}/855: ${(qa&&qa.errors||[]).join('; ')}`);ok(qa&&qa.reactionOK===qa.reactionExpected,`reactions ${qa&&qa.reactionOK}/${qa&&qa.reactionExpected}`);ok(qa&&qa.visualOK===qa.visualExpected,`visuals ${qa&&qa.visualOK}/${qa&&qa.visualExpected}`);
const ids=new Set();let choices=0,termQ=0;for(const x of bank){ok(!ids.has(x.id),`duplicate id ${x.id}`);ids.add(x.id);ok(Array.isArray(x.o)&&x.o.length===5,`${x.id} choices`);ok(Array.isArray(x.e)&&x.e.length===5,`${x.id} explanations`);ok(Number.isInteger(x.a)&&x.a>=0&&x.a<5,`${x.id} answer`);if(Array.isArray(x.o)){choices+=x.o.length;ok(new Set(x.o).size===5,`${x.id} duplicate choice`)}if(Array.isArray(x.e))ok(new Set(x.e).size===5,`${x.id} duplicate explanation`);if(Array.isArray(x.terms)&&x.terms.length)termQ++;}
ok(choices===855,`choice count ${choices}`);ok(termQ>=135,`terms questions ${termQ}`);
const get=id=>bank.find(x=>x.id===id);const batch9=['T33','T34','T35','H32','H33','T36','T37','H34','H35','T38','T39','T40','L32','T41','H36'];for(const id of batch9){const x=get(id);ok(!!x,`${id} missing`);if(x){ok(x.detailGrade==='v7-full',`${id} detail grade`);ok(Array.isArray(x.terms)&&x.terms.length,`${id} terms`);}}
const rx=['H32','H33','H34','H35','H36'];for(const id of rx)ok(get(id)&&Array.isArray(get(id).rxn)&&get(id).rxn.length,`${id} reaction`);ok(get('T36')&&get('T36').v&&get('T36').v.kind==='multiLine','T36 graph');ok(get('T33')&&get('T33').a===2&&/24 mg\/L/.test(get('T33').p),'T33 calculation');ok(get('T35')&&get('T35').a===2&&/100 kg/.test(get('T35').p),'T35 calculation');ok(get('T39')&&get('T39').a===2&&/100 mol/.test(get('T39').p),'T39 calculation');ok(get('T40')&&get('T40').a===3&&/95%/.test(get('T40').p),'T40 calculation');
const loader=fs.readFileSync(path.join(root,'qbank_patch_v5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8');ok(loader.includes('qbank_gap_batch9_v7.js?v=94'),'loader batch9');ok(loader.includes('qbank_detail_quality_fix_v23.js?v=94'),'loader detail fix');ok(sw.includes('qbank_gap_batch9_v7.js'),'service worker batch9');ok(sw.includes('qbank_detail_quality_fix_v23.js'),'service worker detail fix');ok(/localStorage\.setItem/.test(index),'index localStorage save path');ok(/\.ch\.good\{[^}]*#16a34a/.test(index),'green answer CSS');ok(/\.ch\.bad\{[^}]*#dc2626/.test(index),'red answer CSS');ok(/次の問題へ/.test(index),'next-question UI');
const subj={};for(const x of bank)subj[x.s]=(subj[x.s]||0)+1;console.log('BANK',bank.length,'CHOICES',choices,'QUALITY',qa&&`${qa.choiceOK}/${qa.totalChoices}`,'TERMS',termQ,'RX',qa&&`${qa.reactionOK}/${qa.reactionExpected}`,'VIS',qa&&`${qa.visualOK}/${qa.visualExpected}`,'SUBJECTS',JSON.stringify(subj));console.log('BATCH9',batch9.map(id=>`${id}:${get(id).t}`).join(' | '));if(errs.length){console.error('FAIL\n'+errs.join('\n'));process.exit(1)}console.log('PASS Batch9 static quality/regression audit');