const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const scripts=['qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js','qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_gap_batch10_v7.js','qbank_gap_batch11_v7.js','qbank_detail_quality_fix_v23.js'];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],body:{},createElement:()=>({})};
const store=new Map();const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage,Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=localStorage;vm.createContext(ctx);
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
vm.runInContext(fs.readFileSync(path.join(root,'qbank_quality_audit_v7.js'),'utf8'),ctx,{filename:'qbank_quality_audit_v7.js'});
const bank=ctx.window.QBANK,qa=ctx.window.WATER1_QUALITY_AUDIT,errs=[];const ok=(c,m)=>{if(!c)errs.push(m)};
ok(bank.length===191,`question count ${bank.length}`);ok(qa&&qa.totalChoices===955,`choice audit ${qa&&qa.totalChoices}`);ok(qa&&qa.choiceOK===955,`detail ${qa&&qa.choiceOK}/955 ${(qa&&qa.errors||[]).join('; ')}`);ok(qa&&qa.reactionOK===21&&qa.reactionExpected===21,`reactions ${qa&&qa.reactionOK}/${qa&&qa.reactionExpected}`);ok(qa&&qa.visualOK===19&&qa.visualExpected===19,`visuals ${qa&&qa.visualOK}/${qa&&qa.visualExpected}`);
let choices=0,termQ=0;const ids=new Set();for(const x of bank){ok(!ids.has(x.id),`duplicate id ${x.id}`);ids.add(x.id);ok(Array.isArray(x.o)&&x.o.length===5,`${x.id} choices`);ok(Array.isArray(x.e)&&x.e.length===5,`${x.id} explanations`);ok(Number.isInteger(x.a)&&x.a>=0&&x.a<5,`${x.id} answer`);if(Array.isArray(x.o)){choices+=x.o.length;ok(new Set(x.o).size===5,`${x.id} duplicate choice`)}if(Array.isArray(x.e))ok(new Set(x.e).size===5,`${x.id} duplicate explanation`);if(Array.isArray(x.terms)&&x.terms.length)termQ++;}
ok(choices===955,`choice count ${choices}`);ok(termQ>=165,`terms questions ${termQ}`);
const get=id=>bank.find(x=>x.id===id),batch11=['G35','G36','G37','W35','W36','W37','T42','H38','L36','L37'];for(const id of batch11){const x=get(id);ok(!!x,`${id} missing`);if(x){ok(x.detailGrade==='v7-full',`${id} detailGrade`);ok(Array.isArray(x.terms)&&x.terms.length,`${id} terms`);ok(Array.isArray(x.e)&&x.e.every(e=>/^【(正しい|誤り)】/.test(String(e))),`${id} status labels`);}}
const batch11Visual=['G35','G37','W35','W36','H38','L36','L37'];for(const id of batch11Visual)ok(get(id)&&get(id).v,`${id} visual`);ok(get('H38')&&Array.isArray(get('H38').rxn)&&get('H38').rxn.length,'H38 reaction');ok(get('L36')&&Array.isArray(get('L36').rxn)&&get('L36').rxn.length,'L36 reaction');
ok(get('G35')&&get('G35').a===1&&/9\.94億/.test(get('G35').p),'G35 latest GHG');ok(get('G36')&&get('G36').a===1&&/0\.07 ppm/.test(get('G36').p)&&/0\.04 ppm/.test(get('G36').p),'G36 Ox 2026 standard');ok(get('G37')&&get('G37').a===2&&/19,886/.test(get('G37').p)&&/4,508/.test(get('G37').p),'G37 complaint stats');ok(get('W35')&&get('W35').a===1&&/2022年4月/.test(get('W35').p),'W35 E coli standard');ok(get('L36')&&get('L36').a===2&&/8\.0 mgO2\/L/.test(get('L36').p),'L36 calculation');ok(get('L37')&&get('L37').a===1&&/りん/.test(get('L37').p),'L37 limitation');
const subj={};for(const x of bank)subj[x.s]=(subj[x.s]||0)+1;ok(subj['公害総論']===37,`G ${subj['公害総論']}`);ok(subj['水質概論']===37,`W ${subj['水質概論']}`);ok(subj['汚水処理特論']===42,`T ${subj['汚水処理特論']}`);ok(subj['水質有害物質特論']===38,`H ${subj['水質有害物質特論']}`);ok(subj['大規模水質特論']===37,`L ${subj['大規模水質特論']}`);
const loader=fs.readFileSync(path.join(root,'qbank_patch_v5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8');ok(loader.includes('qbank_gap_batch11_v7.js?v=110'),'loader batch11 v110');ok(sw.includes('qbank_gap_batch11_v7.js'),'service worker batch11');ok(/localStorage\.setItem/.test(index),'localStorage save path');ok(/\.ch\.good\{[^}]*#16a34a/.test(index),'green answer CSS');ok(/\.ch\.bad\{[^}]*#dc2626/.test(index),'red answer CSS');ok(/次の問題へ/.test(index),'next UI');ok(/全5肢の解説を開く/.test(index),'all-choice explanation UI');ok(/function save\(\)\{try\{localStorage\.setItem/.test(index),'save function');
localStorage.setItem('probe','ok');ok(localStorage.getItem('probe')==='ok','localStorage probe');localStorage.removeItem('probe');
console.log('BANK',bank.length,'CHOICES',choices,'QUALITY',`${qa.choiceOK}/${qa.totalChoices}`,'TERMS',termQ,'RX',`${qa.reactionOK}/${qa.reactionExpected}`,'VIS',`${qa.visualOK}/${qa.visualExpected}`,'SUBJECTS',JSON.stringify(subj));console.log('BATCH11',batch11.map(id=>`${id}:${get(id).t}`).join(' | '));if(errs.length){console.error('FAIL\n'+errs.join('\n'));process.exit(1)}console.log('PASS Batch11 static quality/UI regression audit');