/* Compile the reviewed content and fixed option permutations; never edit generated JS. */
const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const review=JSON.parse(read('exam_practice_review_v61.json'));
const noop=()=>{};
const document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};
const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);
const scripts=['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])];
for(const f of scripts){if(f==='qbank_review_v62.js'||f==='qbank_primary_source_v63.js'||f==='qbank_exam_practice_v61.js'||f==='ui_polish_v46.js'||f==='study_workflow_v57.js'||f==='compact_menu_v58.js')continue;vm.runInContext(read(f),c,{filename:f});}
const baseline=JSON.parse(JSON.stringify(c.QBANK));
const bank=JSON.parse(JSON.stringify(baseline));
for(const q of bank){const p=review.questions[q.id];if(p){q.q=p.q;q.o=p.o;q.e=p.e;q.a=p.a;}}
// Fixed reference anchors keep documented option numbering and existing browser fixtures.
// Numeric choices and ordinal cross-references are also left in their reviewed order.
const anchors=['G01','G02','G07','G27','G37','G38','H09','H12','L33','L37','T10','T22','T30','T34','T41','W07','W20','W32','W39'];
const pinned=new Set(anchors);
for(const q of bank){
 if(['q','p','o','e'].some(k=>/(?:誤りは|正答[は：:]|正解[は：:]|選択肢\s*)[1-5１-５]|[1-5１-５]番|[①-⑤]/.test(JSON.stringify(q[k]))))pinned.add(q.id);
 if(q.o.every(s=>s.length<24&&/\d/.test(s)))pinned.add(q.id);
}
const targets={G:[8,8,8,8,7],W:[8,8,8,7,8],T:[9,9,8,9,9],H:[8,8,8,8,8],L:[7,7,8,8,7]};
const orders={};
const hash=s=>Array.from(s).reduce((h,ch)=>((h*31+ch.charCodeAt(0))>>>0),613);
for(const [prefix,target] of Object.entries(targets)){
 const qs=bank.filter(q=>q.id[0]===prefix),counts=[0,0,0,0,0];qs.forEach(q=>counts[q.a]++);
 const candidates=qs.filter(q=>!pinned.has(q.id)).sort((a,b)=>hash(a.id)-hash(b.id));
 for(const q of candidates){
  if(counts[q.a]<=target[q.a])continue;
  const deficits=target.map((v,i)=>({i,d:v-counts[i]})).filter(x=>x.d>0).sort((a,b)=>b.d-a.d||((hash(q.id+a.i)%19)-(hash(q.id+b.i)%19)));
  if(!deficits.length)break;
  const dest=deficits[0].i,from=q.a,order=[0,1,2,3,4];[order[from],order[dest]]=[order[dest],order[from]];
  orders[q.id]=order;counts[from]--;counts[dest]++;q.a=dest;
 }
 if(JSON.stringify(counts)!==JSON.stringify(target))throw new Error(prefix+' target unreachable '+counts);
}
const source=`(function(){\n'use strict';\n// Generated by tools/build_exam_practice_v61.js from the reviewed JSON.\nvar edits=${JSON.stringify(review.questions,null,2)};\nvar orders=${JSON.stringify(orders,null,2)};\nvar bank=window.QBANK||[];\nif(window.WATER1_EXAM_PRACTICE_V61)return;\nbank.forEach(function(q){\n var p=edits[q.id];\n if(p){\n  // Keep existing explanatory figures and term widgets; replace only authored prose.\n  var old=String(q.p||''),at=old.search(/<(?:div|details)\\b/),visual=at<0?'':old.slice(at);\n  q.q=p.q;q.o=p.o.slice();q.e=p.e.slice();q.a=p.a;q.p=p.point+(visual?' '+visual:'');\n  q.src=p.basis;q.examPracticeVersion='v61';\n }\n var order=orders[q.id];\n if(order){var opts=q.o.slice(),exps=q.e.slice(),a=q.a;q.o=order.map(function(i){return opts[i]});q.e=order.map(function(i){return exps[i]});q.a=order.indexOf(a);q.choiceOrderVersion='v61';}\n});\n// Pure migration is called by the existing loader before any question is rendered.\n// Counts, bookmarks, due dates, mode, and unknown fields survive unchanged.\nfunction migrate(input){\n var s=JSON.parse(JSON.stringify(input||{}));\n if(s.bankContentVersion==='v61')return s;\n var hist=s.hist||{};\n Object.keys(hist).forEach(function(id){\n  var h=hist[id];if(!h||typeof h!=='object')return;\n  if(edits[id]){\n   if(h.lastSel!==undefined)h.previousContentSelection={version:s.bankContentVersion||'pre-v61',index:h.lastSel};\n   h.lastSel=null;\n  }else if(orders[id]&&Number.isInteger(h.lastSel)&&h.lastSel>=0&&h.lastSel<5){h.lastSel=orders[id].indexOf(h.lastSel);}\n });\n if(edits[s.current]){s.currentAnswered=false;s.currentSel=null;}\n else if(orders[s.current]&&Number.isInteger(s.currentSel)&&s.currentSel>=0&&s.currentSel<5){s.currentSel=orders[s.current].indexOf(s.currentSel);}\n s.bankContentVersion='v61';return s;\n}\nwindow.WATER1_EXAM_PRACTICE_V61={version:'v61',rewritten:Object.keys(edits),orders:orders,migrate:migrate,targets:${JSON.stringify(targets)}};\n})();\n`;
fs.writeFileSync(path.join(root,'qbank_exam_practice_v61.js'),source);
console.log('v61 compiled:',Object.keys(review.questions).length,'rewrites;',Object.keys(orders).length,'permutations');
