const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>JSON.parse(JSON.stringify(x));
function load(with71){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with71&&f==='qbank_coverage_trim_v71.js'))continue;if(f==='qbank_source_audit_v72.js')continue;if(f==='qbank_source_audit_v73.js')continue;if(f==='qbank_source_audit_v74.js')continue;if(f==='qbank_source_audit_v75.js')continue;if(f==='qbank_source_audit_v76.js')continue;if(f==='qbank_source_audit_v77.js')continue;if(f==='qbank_source_audit_v78.js')continue;if(f==='qbank_source_audit_v79.js')continue;if(f==='qbank_source_audit_v80.js')continue;if(f==='qbank_source_audit_v81.js')continue;if(f==='qbank_source_audit_v82.js')continue;if(f==='qbank_source_audit_v83.js')continue;if(f==='qbank_source_audit_v84.js')continue;if(f==='qbank_source_audit_v85.js')continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,archive=after.WATER1_ARCHIVED_QUESTIONS,trim=after.WATER1_COVERAGE_TRIM_V71,ids=['W29','L01','W06','W25'];
assert.equal(before.QBANK.length,198);assert.equal(q.length,194);assert.equal(new Set(q.map(x=>x.id)).size,194);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.filter(x=>!ids.includes(x.id)).map(x=>x.id)));
for(const x of q)assert.deepEqual(plain(x),plain(before.QBANK.find(y=>y.id===x.id)),x.id);
assert.deepEqual(plain(archive.map(x=>x.id)),['L30','T17',...ids]);assert.deepEqual(plain(trim.retired),ids);assert.equal(trim.active,194);assert.equal(new Set([...q,...archive].map(x=>x.id)).size,200);
const expected={W29:['W03','W07'],L01:['W07'],W06:['W01','L06'],W25:['W04']};for(const id of ids){const old=before.QBANK.find(x=>x.id===id),z=archive.find(x=>x.id===id);assert.equal(z.q,old.q);assert.deepEqual(plain(z.o),plain(old.o));assert.deepEqual(plain(z.e),plain(old.e));assert.deepEqual(plain(z.coverageTrim.coveredBy),expected[id]);for(const to of expected[id])assert.ok(q.some(x=>x.id===to));}
const w03=q.find(x=>x.id==='W03'),w07=q.find(x=>x.id==='W07'),w01=q.find(x=>x.id==='W01'),w04=q.find(x=>x.id==='W04');assert.match(w03.q,/Chl-a.*DO/);assert.match(w07.o[w07.a],/鉄.*りん/);assert.match(w01.q,/水温・DO/);assert.match(w04.q,/青白く/);
const counts=[0,0,0,0,0];for(const x of q){assert.equal(x.o.length,5);assert.equal(x.e.length,5);counts[x.a]++;}assert.deepEqual(counts,[38,38,40,40,38]);
for(const id of ids)for(const version of ['v61','v70']){const s={bankContentVersion:version,hist:{[id]:{attempts:5,correct:2,lastSel:1,dueAt:1900000000000}},total:8,correct:4,current:id,currentSel:1,currentAnswered:true,reviewFlags:{[id]:true},other:{keep:1}};const original=JSON.stringify(s),z=trim.migrate(s);assert.equal(JSON.stringify(s),original);assert.equal(z.bankContentVersion,'v71');assert.equal(z.current,null);assert.equal(z.currentSel,null);assert.equal(z.currentAnswered,false);assert.equal(z.hist[id].attempts,5);assert.equal(z.hist[id].dueAt,1900000000000);assert.equal(z.total,8);assert.deepEqual(plain(z.other),s.other);assert.deepEqual(plain(trim.migrate(z)),plain(z));}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_coverage_trim_v71.js')>assets.indexOf('qbank_source_audit_v70.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v96'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archive.map(x=>x.id),distribution:counts,migrationCases:8,offlineAssets:assets.length}));
