const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>JSON.parse(JSON.stringify(x));
function load(with68){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js','qbank_source_audit_v69.js','qbank_source_audit_v70.js'].includes(f)||(!with68&&f==='qbank_coverage_trim_v68.js'))continue;if(f==='qbank_coverage_trim_v71.js')continue;if(f==='qbank_source_audit_v72.js')continue;if(f==='qbank_source_audit_v73.js')continue;if(f==='qbank_source_audit_v74.js')continue;if(f==='qbank_source_audit_v75.js')continue;if(f==='qbank_source_audit_v76.js')continue;if(f==='qbank_source_audit_v77.js')continue;if(f==='qbank_source_audit_v78.js')continue;if(f==='qbank_source_audit_v79.js')continue;if(f==='qbank_source_audit_v80.js')continue;if(f==='qbank_source_audit_v81.js')continue;if(f==='qbank_source_audit_v82.js')continue;if(f==='qbank_source_audit_v83.js')continue;if(f==='qbank_source_audit_v84.js')continue;if(f==='qbank_source_audit_v85.js')continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,archive=after.WATER1_ARCHIVED_QUESTIONS,trim=after.WATER1_COVERAGE_TRIM_V68;
assert.equal(before.QBANK.length,199);assert.equal(q.length,198);assert.equal(new Set(q.map(x=>x.id)).size,198);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.filter(x=>x.id!=='T17').map(x=>x.id)));
for(const x of q)assert.deepEqual(plain(x),plain(before.QBANK.find(y=>y.id===x.id)),x.id);
assert.deepEqual(plain(archive.map(x=>x.id)),['L30','T17']);assert.deepEqual(plain(trim.retired),['T17']);assert.equal(trim.active,198);
const old=before.QBANK.find(x=>x.id==='T17'),retired=archive.find(x=>x.id==='T17');assert.equal(retired.q,old.q);assert.deepEqual(plain(retired.o),plain(old.o));assert.deepEqual(plain(retired.e),plain(old.e));assert.deepEqual(plain(retired.coverageTrim.coveredBy),['T34','T43']);
const tp=q.find(x=>x.id==='T34'),tn=q.find(x=>x.id==='T43');assert.match(tp.q,/全りん/);assert.match(tp.o[tp.a],/ろ過/);assert.match(tp.e[tp.a],/懸濁態/);assert.match(tn.q,/全窒素/);assert.match(tn.o[tn.a],/ろ過/);assert.match(tn.e[tn.a],/溶存態/);
const counts=[0,0,0,0,0];for(const x of q){assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);counts[x.a]++;}assert.deepEqual(counts,[39,40,40,40,39]);
for(const version of ['v61','v66','v67'])for(let selected=0;selected<5;selected++){
 const s={bankContentVersion:version,hist:{T17:{attempts:7,correct:3,wrong:4,lastSel:selected,dueAt:1900000000000},T34:{attempts:2,lastSel:selected}},total:99,correct:65,current:'T17',currentSel:selected,currentAnswered:true,mode:'weak',reviewFlags:{T17:true},other:{keep:1}};
 const copy=JSON.stringify(s),z=trim.migrate(s);assert.equal(JSON.stringify(s),copy);assert.equal(z.bankContentVersion,'v68');assert.equal(z.total,99);assert.equal(z.correct,65);assert.equal(z.current,null);assert.equal(z.currentAnswered,false);assert.equal(z.currentSel,null);assert.equal(z.hist.T17.attempts,7);assert.equal(z.hist.T17.correct,3);assert.equal(z.hist.T17.dueAt,1900000000000);assert.deepEqual(plain(z.reviewFlags),s.reviewFlags);assert.deepEqual(plain(z.other),s.other);if(version==='v67')assert.equal(z.hist.T17.lastSel,selected);assert.deepEqual(plain(trim.migrate(z)),plain(z));
}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_coverage_trim_v68.js','qbank_source_audit_v69.js','qbank_source_audit_v70.js')>assets.indexOf('qbank_source_audit_v67.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v96'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archive.map(x=>x.id),distribution:counts,migrationCases:15,offlineAssets:assets.length,coverage:{T17:['T34','T43']}}));
