const fs=require('fs'),vm=require('vm'),path=require('path');
const root=process.argv[2]?path.resolve(process.argv[2]):path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function ok(cond,msg){if(!cond){console.error('FAIL',msg);process.exit(1)}}
const ctx={window:{}};vm.createContext(ctx);
for(let i=1;i<=11;i++)vm.runInContext(read(`glossary-v5-pack-${String(i).padStart(2,'0')}.js`),ctx,{filename:`pack-${i}`});
vm.runInContext(read('glossary-v5-term-loader.js'),ctx,{filename:'term-loader'});
for(const f of ['glossary-v5-sampling.js','glossary-v5-analysis-1.js','glossary-v5-analysis-2.js','glossary-v5-refs.js','glossary-v5-jis.js','glossary-v5-diagrams.js','glossary-v5-samplingDiagrams.js'])vm.runInContext(read(f),ctx,{filename:f});
const T=ctx.window.GLOSSARY_TERMS||[], D=ctx.window.GLOSSARY_V5||{};
const html=read('glossary-v5.html'), app=read('glossary-v5-app.js');
ok(T.length===735,`terms ${T.length} != 735`);
ok(new Set(T.map(x=>x.term)).size===735,'term names are not unique');
ok((D.sampling||[]).length===36,`sampling ${(D.sampling||[]).length} != 36`);
ok((D.analysis||[]).length===40,`analysis ${(D.analysis||[]).length} != 40`);
ok((D.refs||[]).length===19,`refs ${(D.refs||[]).length} != 19`);
ok(T.some(x=>x.term==='六価クロム'),'六価クロム missing');
ok((D.analysis||[]).some(x=>x.target==='六価クロム'),'reverse/analysis 六価クロム target missing');
ok(Object.keys(D.jis||{}).includes('K0102-3'),'K0102-3 JIS mapping missing');
const packs=[...html.matchAll(/glossary-v5-pack-(\d{2})\.js/g)].map(m=>m[1]);
ok(packs.length===11,`HTML pack refs ${packs.length} != 11`);
ok(packs.join(',')==='01,02,03,04,05,06,07,08,09,10,11','pack load order is incomplete/wrong');
ok(html.includes('glossary-v5-term-loader.js'),'term loader not referenced');
ok(html.includes('glossary-v5-analysis-1.js')&&html.includes('glossary-v5-analysis-2.js'),'analysis split files not both referenced');
ok(!/glossary-v5-terms-(0[7-9]|1[0-4])\.js/.test(html),'obsolete missing term files referenced');
ok(html.includes('html{scroll-behavior:auto}'),'reliable immediate jump CSS missing');
for(const s of ['function gotoTerm(t)','data-termjump','scrollTop:false','requestAnimationFrame(()=>scrollToId','function candidates(q)','function renderSuggestions(q)','sampling:(D.sampling||[])','analysis:(D.analysis||[])','reverse:revTargets','refs:(D.refs||[])'])ok(app.includes(s),`app regression token missing: ${s}`);
ok(app.includes("input.addEventListener('input'"),'search input handler missing');
ok(app.includes("suggest.addEventListener('click'"),'suggestion click handler missing');
ok(app.includes('window.GLOSSARY_V5_READY'),'runtime readiness info missing');
console.log(`TERMS ${T.length} SAMPLING ${D.sampling.length} ANALYSIS ${D.analysis.length} REFS ${D.refs.length} PACKS ${packs.length}`);
console.log('PASS glossary v5 data/search/reverse-jump regression audit');
