const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const files=['qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js','qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_gap_batch10_v7.js','qbank_gap_batch11_v7.js','qbank_gap_batch12_v7.js','qbank_detail_quality_fix_v23.js','qbank_undefined_fix_v7.js','qbank_exam_quality_patch_v34.js','qbank_visual_fix_v35.js','qbank_unit_typography_v1.js','qbank_content_restructure_v39.js','qbank_distractor_plausibility_v40.js','qbank_semantic_rewrite_gw_v42.js','qbank_semantic_rewrite_th_v42.js','qbank_semantic_rewrite_l_v42.js','qbank_semantic_strengthen_g_v42.js','qbank_semantic_strengthen_w_v42.js','qbank_semantic_strengthen_t_v42.js','qbank_semantic_strengthen_h_v42.js','qbank_semantic_strengthen_l_v42.js','qbank_semantic_polish_v43.js','qbank_semantic_polish_v44.js','qbank_semantic_polish_v45.js','qbank_exam_difficulty_stage1_v47.js','qbank_recent_exam_upgrade_v47.js','qbank_recent_exam_audit_finalize_v47.js','qbank_exam_difficulty_stage2_v48.js','qbank_exam_difficulty_stage3_v49.js','qbank_exam_difficulty_stage3_fix_v49.js','qbank_exam_difficulty_stage4_v50.js','qbank_exam_difficulty_stage5_v51.js','qbank_learning_visuals_v52.js','visual_aid_audit_v53.js','qbank_learning_visuals_v53.js','qbank_learning_visuals_v53_mobilefix.js','qbank_direct_visual_difficulty_v54.js','qbank_direct_visual_quality_v55.js'];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],querySelector:()=>null,body:{},head:{appendChild:noop},createElement:()=>({style:{},setAttribute:noop,appendChild:noop})};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage:{getItem:()=>null,setItem:noop,removeItem:noop},Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=ctx.localStorage;vm.createContext(ctx);
for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const ids=['G01','G02','G07','G29'],baseline={};for(const id of ids){const q=ctx.window.QBANK.find(x=>x.id===id);if(q)baseline[id]=q.a;}
vm.runInContext(fs.readFileSync(path.join(root,'qbank_legal_fillin_v56.js'),'utf8'),ctx,{filename:'qbank_legal_fillin_v56.js'});
const bank=ctx.window.QBANK||[],arc=ctx.window.WATER1_ARCHIVED_QUESTIONS||[],errs=[];const ok=(c,m)=>{if(!c)errs.push(m)};
ok(bank.length===199,`active bank changed: ${bank.length}`);ok(arc.length===1&&arc[0].id==='L30','archive invariant failed');
for(const id of ids){const q=bank.find(x=>x.id===id);ok(!!q,`${id} missing`);if(!q)continue;ok(q.s==='公害総論',`${id} subject changed`);ok(q.legalFillinVersion==='v56',`${id} marker missing`);ok(q.a===baseline[id],`${id} answer index changed`);ok(/組合せ/.test(q.q),`${id} not combination format`);ok(/（ア）/.test(q.q)&&/（イ）/.test(q.q)&&/（ウ）/.test(q.q),`${id} lacks 3+ blanks`);ok(Array.isArray(q.o)&&q.o.length===5,`${id} choices !=5`);ok(Array.isArray(q.e)&&q.e.length===5,`${id} explanations !=5`);ok(new Set(q.o).size===5,`${id} duplicate choices`);ok(new Set(q.e).size===5,`${id} duplicate explanations`);ok(q.v==null&&q.av==null,`${id} stale visual remains`);q.e.forEach((e,i)=>{ok(String(e).length>=100,`${id}.e${i+1} too short`);ok(String(e).startsWith(i===q.a?'【正しい】':'【誤り】'),`${id}.e${i+1} status prefix`);});}
const g01=bank.find(x=>x.id==='G01'),g02=bank.find(x=>x.id==='G02'),g07=bank.find(x=>x.id==='G07'),g29=bank.find(x=>x.id==='G29');
ok(g01.o[g01.a].includes('条件')&&g01.o[g01.a].includes('保護')&&g01.o[g01.a].includes('保全'),'G01 legal wording');
ok(g02.o[g02.a].includes('熱')&&g02.o[g02.a].includes('都道府県')&&g02.o[g02.a].includes('条例')&&g02.o[g02.a].includes('許容限度'),'G02 legal wording');
ok(g07.o[g07.a].includes('60')&&g07.o[g07.a].includes('30')&&g07.o[g07.a].includes('20'),'G07 deadlines');
ok(g29.o[g29.a].includes('基本理念')&&g29.o[g29.a].includes('総合的かつ計画的')&&g29.o[g29.a].includes('健康で文化的'),'G29 purpose wording');
const meta=ctx.window.WATER1_LEGAL_FILLIN_AUDIT||{};ok(meta.version==='v56','metadata version');ok(Array.isArray(meta.targetIds)&&ids.every(id=>meta.targetIds.includes(id)),'metadata ids');ok(Array.isArray(meta.confirmedPatterns)&&meta.confirmedPatterns.length>=5,'historical pattern metadata');
const loader=fs.readFileSync(path.join(root,'qbank_patch_v5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),analysis=fs.readFileSync(path.join(root,'analysis_legal_fillin_2006_2025_v56.md'),'utf8');
ok(loader.includes('qbank_legal_fillin_v56.js?v=154'),'loader missing v56');ok(sw.includes('qbank_legal_fillin_v56.js'),'service worker missing v56');ok(index.includes("KEY='water1_bank_v3'"),'history key changed');ok(/2006.*2025/.test(analysis)&&analysis.includes('R06')&&analysis.includes('R07'),'20-year audit note incomplete');
console.log('LEGAL_FILLIN_V56',ids.join(','),'ACTIVE',bank.length,'ARCHIVED',arc.length,'STABLE',bank.length+arc.length);
if(errs.length){console.error('FAIL v56 legal fill-in audit\n'+errs.join('\n'));process.exit(1)}console.log('PASS v56 legal fill-in / word-combination audit');
