const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>JSON.parse(JSON.stringify(x));
function load(with96){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with96&&f==='qbank_public_restore_v96.js'))continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,archive=after.WATER1_ARCHIVED_QUESTIONS,review=after.WATER1_PUBLIC_RESTORE_V96,snapshot=after.WATER1_PUBLISHED_QUESTION_SNAPSHOT_V96;
assert.equal(before.QBANK.length,185);assert.equal(q.length,186);assert.equal(archive.length,14);assert.equal(new Set([...q,...archive].map(x=>x.id)).size,200);assert.equal(snapshot.length,19);assert.equal(review.changed.length,19);
assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.flatMap(x=>x.id==='H39'?[x.id,'H40']:[x.id])));assert.ok(q.some(x=>x.id==='H40'));assert.deepEqual(plain(archive.map(x=>x.id)),plain(before.WATER1_ARCHIVED_QUESTIONS.filter(x=>x.id!=='H40').map(x=>x.id)));
for(const x of q){const old=before.QBANK.find(y=>y.id===x.id)||before.WATER1_ARCHIVED_QUESTIONS.find(y=>y.id===x.id);assert.equal(x.a,old.a,x.id);assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);assert.equal(new Set(x.o).size,5,x.id);assert.ok(x.e.every(s=>typeof s==='string'&&s.length>0),x.id);assert.match(x.src,/https:\/\//,x.id);if(review.changed.includes(x.id)){const pub=snapshot.find(z=>z.id===x.id).question;for(const key of ['q','o','e','p','src','v','t','terms','rxn'])assert.deepEqual(plain(x[key]===undefined?null:x[key]),plain(pub[key]===undefined?null:pub[key]),x.id+':'+key);assert.equal(x.contentReviewVersion,'v96');assert.match(x.primarySourceReviewVersion,/v6[34]/);}else assert.deepEqual(plain(x),plain(old),x.id);}
for(const version of ['v61','v64','v95'])for(const id of review.changed)for(let sel=0;sel<5;sel++){const state={bankContentVersion:version,hist:{[id]:{attempts:5,correct:2,wrong:3,lastSel:sel,dueAt:1900000000000}},current:id,currentSel:sel,currentAnswered:true},original=JSON.stringify(state),result=review.migrate(state);assert.equal(JSON.stringify(state),original);assert.equal(result.bankContentVersion,'v96');assert.equal(result.hist[id].lastSel,null);assert.equal(result.hist[id].attempts,5);assert.equal(result.hist[id].correct,2);assert.equal(result.hist[id].wrong,3);assert.equal(result.currentAnswered,false);assert.equal(result.currentSel,null);assert.deepEqual(plain(review.migrate(result)),plain(result));}
const assets=Array.from(read('sw.js').matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.includes('qbank_review_v63.js'));assert.ok(assets.includes('qbank_review_v64.js'));assert.ok(assets.includes('qbank_public_restore_v96.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v96'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archive.length,publishedRestored:review.changed.length,historyCases:285,offlineAssets:assets.length}));
