const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const scripts=['qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js','qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_gap_batch10_v7.js','qbank_gap_batch11_v7.js','qbank_gap_batch12_v7.js','qbank_detail_quality_fix_v23.js','qbank_undefined_fix_v7.js','qbank_exam_quality_patch_v34.js','qbank_visual_fix_v35.js','qbank_unit_typography_v1.js','qbank_content_restructure_v39.js','qbank_distractor_plausibility_v40.js','qbank_semantic_rewrite_gw_v42.js','qbank_semantic_rewrite_th_v42.js','qbank_semantic_rewrite_l_v42.js','qbank_semantic_strengthen_g_v42.js','qbank_semantic_strengthen_w_v42.js','qbank_semantic_strengthen_t_v42.js','qbank_semantic_strengthen_h_v42.js','qbank_semantic_strengthen_l_v42.js','qbank_semantic_polish_v43.js','qbank_semantic_polish_v44.js','qbank_semantic_polish_v45.js','qbank_recent_exam_upgrade_v47.js'];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],body:{},createElement:()=>({})};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage:{getItem:()=>null,setItem:noop,removeItem:noop},Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=ctx.localStorage;vm.createContext(ctx);
for(const f of scripts)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const bank=ctx.window.QBANK||[],arc=ctx.window.WATER1_ARCHIVED_QUESTIONS||[],meta=ctx.window.WATER1_RECENT_EXAM_DIFFICULTY_AUDIT||{};
function fail(s){throw new Error(s)}function ok(c,s){if(!c)fail(s)}
const expected=['G01','G02','G07','G15','G17','G19','W01','W11','W17','W20','W26','T05','T10','T12','T16','T21','H09','H16','H21','H24','H25','L04','L05','L07','L23','L26'];
const expectedAnswer={G01:0,G02:0,G07:0,G15:0,G17:0,G19:0,W01:3,W11:1,W17:1,W20:0,W26:3,T05:3,T10:4,T12:0,T16:3,T21:4,H09:3,H16:0,H21:1,H24:0,H25:0,L04:4,L05:0,L07:0,L23:0,L26:0};
ok(bank.length===199,'active bank must remain 199, got '+bank.length);ok(arc.length===1&&arc[0].id==='L30','archived L30 invariant failed');
ok(meta.version==='v47'&&meta.window==='2020-2025','v47 audit metadata missing');ok(meta.reviewedActive===199,'not all 199 active questions were stamped reviewed');
ok(Array.isArray(meta.upgradedIds)&&meta.upgradedIds.length===expected.length,'upgrade count mismatch');ok(expected.every(id=>meta.upgradedIds.includes(id)),'expected upgraded ID missing');
const ids=new Set();for(const x of bank){ok(!ids.has(x.id),'duplicate ID '+x.id);ids.add(x.id);ok(x.recentExamDifficultyAudit&&x.recentExamDifficultyAudit.version==='v47','unreviewed active ID '+x.id);ok(x.recentExamDifficultyAudit.window==='2020-2025','wrong comparison window '+x.id);ok(['MATCH_RECENT_EXAM_LEVEL','UPGRADED_TO_RECENT_EXAM_LEVEL'].includes(x.recentExamDifficultyAudit.status),'invalid status '+x.id);ok(Array.isArray(x.o)&&x.o.length===5,'not five choices '+x.id);ok(Array.isArray(x.e)&&x.e.length===5,'not five explanations '+x.id);ok(Number.isInteger(x.a)&&x.a>=0&&x.a<5,'invalid answer '+x.id);}
const changed=bank.filter(x=>x.recentExamDifficultyAudit.status==='UPGRADED_TO_RECENT_EXAM_LEVEL');ok(changed.length===26,'expected 26 upgraded questions, got '+changed.length);
const bySubject={};const byKind={};for(const x of changed){bySubject[x.s]=(bySubject[x.s]||0)+1;byKind[x.recentExamUpgradeKind]=(byKind[x.recentExamUpgradeKind]||0)+1;ok(x.recentExamUpgradeVersion==='v47','upgrade version missing '+x.id);ok(x.recentExamBasis&&x.recentExamBasis.length>=20,'comparison basis too thin '+x.id);ok(x.a===expectedAnswer[x.id],'answer index changed for '+x.id);ok(new Set(x.o).size===5,'duplicate choice '+x.id);ok(new Set(x.e).size===5,'duplicate explanation '+x.id);for(let i=0;i<5;i++){ok(/^【(正しい|誤り)】/.test(x.e[i]),'explanation label missing '+x.id+' choice '+(i+1));if(i===x.a)ok(/^【正しい】/.test(x.e[i]),'correct explanation mismatch '+x.id);else ok(/^【誤り】/.test(x.e[i]),'wrong explanation mismatch '+x.id+' choice '+(i+1));}}
ok(bySubject['公害総論']===6&&bySubject['水質概論']===5&&bySubject['汚水処理特論']===5&&bySubject['水質有害物質特論']===5&&bySubject['大規模水質特論']===5,'subject upgrade balance mismatch '+JSON.stringify(bySubject));
const visualChanged=changed.filter(x=>x.v).length;ok(visualChanged>=5,'not enough upgraded data/table questions: '+visualChanged);
const calcKinds=(byKind.CALC||0)+(byKind.CALC_TABLE||0)+(byKind.STOICHIOMETRY||0)+(byKind.MODEL_EQUATION||0);ok(calcKinds>=5,'not enough calculation/model upgrades: '+calcKinds);
const lawKinds=byKind.LEGAL_CASE||0;ok(lawKinds>=6,'not enough legal-case upgrades: '+lawKinds);
const analysisKinds=byKind.ANALYTICAL_OPERATION||0;ok(analysisKinds>=4,'not enough analytical-operation upgrades: '+analysisKinds);
ok(arc[0].recentExamDifficultyAudit&&arc[0].recentExamDifficultyAudit.status==='ARCHIVED_EXCLUDED','archive review metadata missing');
console.log('RECENT_EXAM_REVIEWED',bank.length,'ARCHIVED',arc.map(x=>x.id).join(','));
console.log('RECENT_EXAM_UPGRADED',changed.length,expected.join(','));
console.log('RECENT_EXAM_BY_SUBJECT',JSON.stringify(bySubject));
console.log('RECENT_EXAM_BY_KIND',JSON.stringify(byKind));
console.log('RECENT_EXAM_VISUAL_UPGRADES',visualChanged);
console.log('PASS 2020-2025 recent-exam difficulty audit v47');
