const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with89){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with89&&f==='qbank_source_audit_v89.js'))continue;if(f==='qbank_source_audit_v90.js')continue;if(f==='qbank_source_audit_v91.js')continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),ids=['L18','L19','G20','G21','G22','H21','H22'],q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V89,archived=after.WATER1_ARCHIVED_QUESTIONS;
assert.equal(before.QBANK.length,191);assert.equal(q.length,190);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(review.retired),['H20']);assert.deepEqual(plain(review.coveredBy),['H08']);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.filter(x=>x.id!=='H20').map(x=>x.id)));
assert.deepEqual(plain(archived.map(x=>x.id)),['L30','T17','W29','L01','W06','W25','L04','L10','L06','H20']);assert.equal(new Set([...q,...archived].map(x=>x.id)).size,200);
for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);assert.equal(x.a,old.a,x.id);assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);if(ids.includes(x.id)){assert.equal(x.q,old.q);assert.deepEqual(plain(x.v),plain(old.v));assert.deepEqual(plain(x.o),plain(old.o));assert.deepEqual(plain(x.e),plain(old.e));assert.equal(x.p,old.p);assert.equal(x.contentReviewVersion,'v89');assert.match(x.src,/US EPA|USGS|環境省/);}else assert.deepEqual(plain(x),plain(old),x.id);}
const old=before.QBANK.find(x=>x.id==='H20'),z=archived.at(-1);assert.equal(z.q,old.q);assert.deepEqual(plain(z.o),plain(old.o));assert.deepEqual(plain(z.e),plain(old.e));assert.ok(q.some(x=>x.id==='H08'));assert.match(q.find(x=>x.id==='H08').q,/EDTA/);
const counts=[0,0,0,0,0];for(const x of q)counts[x.a]++;assert.deepEqual(counts,[38,37,40,38,37]);
for(const version of ['v61','v87','v88'])for(let sel=0;sel<5;sel++){const s={bankContentVersion:version,hist:{H20:{attempts:5,lastSel:sel,dueAt:1900000000000},L18:{lastSel:sel}},total:9,current:'H20',currentSel:sel,currentAnswered:true,other:{keep:1}},original=JSON.stringify(s),r=review.migrate(s);assert.equal(JSON.stringify(s),original);assert.equal(r.bankContentVersion,'v89');assert.equal(r.current,null);assert.equal(r.currentSel,null);assert.equal(r.currentAnswered,false);assert.equal(r.hist.H20.attempts,5);assert.equal(r.hist.H20.lastSel,sel);assert.equal(r.hist.H20.dueAt,1900000000000);assert.equal(r.hist.L18.lastSel,sel);assert.deepEqual(plain(r.other),s.other);assert.deepEqual(plain(review.migrate(r)),plain(r));}
for(const id of ids){const s={bankContentVersion:'v88',hist:{[id]:{lastSel:2}},current:id,currentSel:2,currentAnswered:true};const baseline=before.WATER1_EXAM_PRACTICE_V61.migrate(s),r=review.migrate(s);assert.equal(r.current,baseline.current);assert.equal(r.currentSel,baseline.currentSel);assert.equal(r.currentAnswered,baseline.currentAnswered);assert.equal(r.hist[id].lastSel,baseline.hist[id].lastSel);}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v89.js')>assets.indexOf('qbank_source_audit_v88.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v97'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archived.length,reviewed:7,choices:35,retired:['H20'],distribution:counts,migrationCases:22,offlineAssets:assets.length}));
