const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with91){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with91&&f==='qbank_source_audit_v91.js'))continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V91,ids=['L23','L24','L25','G26','G27','G28','W28','H26','H27'];
assert.equal(before.QBANK.length,190);assert.equal(q.length,190);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(review.stale),[]);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.map(x=>x.id)));
assert.deepEqual(plain(after.WATER1_ARCHIVED_QUESTIONS.map(x=>x.id)),['L30','T17','W29','L01','W06','W25','L04','L10','L06','H20']);assert.equal(new Set([...q,...after.WATER1_ARCHIVED_QUESTIONS].map(x=>x.id)).size,200);
for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);if(ids.includes(x.id)){assert.equal(x.a,old.a,x.id);assert.equal(x.q,old.q,x.id);assert.deepEqual(plain(x.v),plain(old.v),x.id);assert.deepEqual(plain(x.o),plain(old.o),x.id);assert.deepEqual(plain(x.e),plain(old.e),x.id);assert.equal(x.p,old.p,x.id);assert.equal(x.contentReviewVersion,'v91');assert.match(x.src,/US EPA|USGS|経済産業省|ATSDR|環境省/);}else assert.deepEqual(plain(x),plain(old),x.id);}
const counts=[0,0,0,0,0];for(const x of q)counts[x.a]++;assert.deepEqual(counts,[38,37,40,38,37]);
for(const version of ['v61','v89','v90'])for(const id of ids)for(let sel=0;sel<5;sel++){const state={bankContentVersion:version,hist:{[id]:{attempts:4,lastSel:sel,dueAt:1900000000000}},total:99,current:id,currentSel:sel,currentAnswered:true},original=JSON.stringify(state),baseline=before.WATER1_EXAM_PRACTICE_V61.migrate(state),z=review.migrate(state);assert.equal(JSON.stringify(state),original);assert.equal(z.bankContentVersion,'v91');assert.equal(z.current,baseline.current);assert.equal(z.currentSel,baseline.currentSel);assert.equal(z.currentAnswered,baseline.currentAnswered);assert.equal(z.hist[id].lastSel,baseline.hist[id].lastSel);assert.equal(z.hist[id].attempts,baseline.hist[id].attempts);assert.deepEqual(plain(review.migrate(z)),plain(z));}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v91.js')>assets.indexOf('qbank_source_audit_v90.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v98'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:10,reviewed:9,choices:45,distribution:counts,migrationCases:135,offlineAssets:assets.length}));
