const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with70){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with70&&f==='qbank_source_audit_v70.js'))continue;if(f==='qbank_coverage_trim_v71.js')continue;if(f==='qbank_source_audit_v72.js')continue;if(f==='qbank_source_audit_v73.js')continue;if(f==='qbank_source_audit_v74.js')continue;if(f==='qbank_source_audit_v75.js')continue;if(f==='qbank_source_audit_v76.js')continue;if(f==='qbank_source_audit_v77.js')continue;if(f==='qbank_source_audit_v78.js')continue;if(f==='qbank_source_audit_v79.js')continue;if(f==='qbank_source_audit_v80.js')continue;if(f==='qbank_source_audit_v81.js')continue;if(f==='qbank_source_audit_v82.js')continue;if(f==='qbank_source_audit_v83.js')continue;if(f==='qbank_source_audit_v84.js')continue;if(f==='qbank_source_audit_v85.js')continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_source_audit_v89.js')continue;if(f==='qbank_source_audit_v90.js')continue;if(f==='qbank_source_audit_v91.js')continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V70,ids=['T25','T26','T27','T28','T29'];
assert.equal(before.QBANK.length,198);assert.equal(q.length,198);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.map(x=>x.id)));
assert.deepEqual(plain(after.WATER1_ARCHIVED_QUESTIONS.map(x=>x.id)),['L30','T17']);
let changed=0;for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);if(ids.includes(x.id)){changed++;assert.equal(x.a,old.a,x.id);assert.deepEqual(plain(x.v),plain(old.v),x.id);assert.equal(x.o.length,5);assert.equal(x.e.length,5);assert.equal(x.contentReviewVersion,'v70');assert.match(x.src,/US EPA|環境省/);}else assert.deepEqual(plain(x),plain(old),x.id);}assert.equal(changed,5);
const counts=[0,0,0,0,0];for(const x of q){assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);counts[x.a]++;}assert.deepEqual(counts,[39,40,40,40,39]);
for(const version of ['v61','v68','v69'])for(let sel=0;sel<5;sel++){
 const s={bankContentVersion:version,hist:{T25:{attempts:4,correct:2,lastSel:sel,dueAt:1900000000000},T26:{attempts:3,lastSel:sel},T17:{attempts:5,lastSel:1}},total:99,correct:65,current:'T25',currentSel:sel,currentAnswered:true,reviewFlags:{T25:true},other:{keep:1}};
 const original=JSON.stringify(s),z=review.migrate(s);assert.equal(JSON.stringify(s),original);assert.equal(z.bankContentVersion,'v70');assert.equal(z.total,99);assert.equal(z.correct,65);assert.equal(z.current,'T25');assert.equal(z.currentAnswered,false);assert.equal(z.currentSel,null);assert.equal(z.hist.T25.lastSel,null);assert.equal(z.hist.T25.previousV69Selection.index,sel);assert.equal(z.hist.T25.attempts,4);assert.equal(z.hist.T25.dueAt,1900000000000);assert.equal(z.hist.T26.lastSel,null);if(version==='v69')assert.equal(z.hist.T17.lastSel,1);assert.deepEqual(plain(z.reviewFlags),s.reviewFlags);assert.deepEqual(plain(z.other),s.other);assert.deepEqual(plain(review.migrate(z)),plain(z));
}
for(const id of ids){const z=review.migrate({bankContentVersion:'v69',hist:{},current:id,currentAnswered:true,currentSel:0});assert.equal(z.currentAnswered,false);assert.equal(z.currentSel,null);}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v70.js')>assets.indexOf('qbank_source_audit_v69.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v96'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:['L30','T17'],changed:ids,choices:25,distribution:counts,migrationCases:20,offlineAssets:assets.length}));
