const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>JSON.parse(JSON.stringify(x));
function load(with66){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js','qbank_source_audit_v67.js','qbank_coverage_trim_v68.js','qbank_source_audit_v69.js','qbank_source_audit_v70.js'].includes(f)||(!with66&&f==='qbank_source_audit_v66.js'))continue;if(f==='qbank_coverage_trim_v71.js')continue;if(f==='qbank_source_audit_v72.js')continue;if(f==='qbank_source_audit_v73.js')continue;if(f==='qbank_source_audit_v74.js')continue;if(f==='qbank_source_audit_v75.js')continue;if(f==='qbank_source_audit_v76.js')continue;if(f==='qbank_source_audit_v77.js')continue;if(f==='qbank_source_audit_v78.js')continue;if(f==='qbank_source_audit_v79.js')continue;if(f==='qbank_source_audit_v80.js')continue;if(f==='qbank_source_audit_v81.js')continue;if(f==='qbank_source_audit_v82.js')continue;if(f==='qbank_source_audit_v83.js')continue;if(f==='qbank_source_audit_v84.js')continue;if(f==='qbank_source_audit_v85.js')continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_source_audit_v89.js')continue;if(f==='qbank_source_audit_v90.js')continue;if(f==='qbank_source_audit_v91.js')continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const prev=load(false),now=load(true),q=now.QBANK,rev=now.WATER1_SOURCE_AUDIT_V66;
assert.equal(q.length,199);assert.equal(new Set(q.map(x=>x.id)).size,199);
assert.deepEqual(plain(q.map(x=>x.id)),plain(prev.QBANK.map(x=>x.id)));
assert.deepEqual(plain(now.WATER1_ARCHIVED_QUESTIONS),plain(prev.WATER1_ARCHIVED_QUESTIONS));
assert.deepEqual(plain(rev.changed),['T08','T09','T11','T12','T14']);
assert.deepEqual(plain(rev.stale),plain(rev.changed));
const counts=[0,0,0,0,0],before=id=>prev.QBANK.find(x=>x.id===id);
for(const x of q){assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);assert.equal(new Set(x.o).size,5,x.id);assert.equal(new Set(x.e).size,5,x.id);assert.equal(x.a,before(x.id).a,x.id);assert.deepEqual(plain(x.v||null),plain(before(x.id).v||null),x.id);counts[x.a]++;if(rev.changed.includes(x.id)){assert.ok(x.e.every(v=>v.length>35),x.id);assert.notDeepEqual(plain(x.o),plain(before(x.id).o),x.id);assert.match(x.src,/https:\/\//);}else assert.deepEqual(plain(x),plain(before(x.id)),x.id);}
assert.deepEqual(counts,[40,40,40,40,39]);
for(const version of ['v61','v62','v63','v64','v65'])for(let selected=0;selected<5;selected++){
 const s={bankContentVersion:version,hist:{},total:99,correct:65,current:'T08',currentSel:selected,currentAnswered:true,mode:'weak',reviewFlags:{T08:true},other:{keep:1}};
 for(const x of q)s.hist[x.id]={attempts:3,correct:2,wrong:1,lastSel:selected,dueAt:1900000000000};s.hist.L30={lastSel:selected};
 const copy=JSON.stringify(s),z=rev.migrate(s);assert.equal(JSON.stringify(s),copy);assert.equal(z.bankContentVersion,'v66');assert.equal(z.total,99);assert.equal(z.correct,65);assert.deepEqual(plain(z.other),s.other);assert.deepEqual(plain(z.reviewFlags),s.reviewFlags);
 for(const id of rev.stale){assert.equal(z.hist[id].lastSel,null,id);assert.equal(z.hist[id].attempts,3);assert.equal(z.hist[id].dueAt,1900000000000);if(version==='v65')assert.equal(z.hist[id].previousV65Selection.index,selected);}
 assert.equal(z.currentAnswered,false);assert.equal(z.currentSel,null);assert.equal(z.hist.L30.lastSel,selected);assert.deepEqual(plain(rev.migrate(z)),plain(z));
 if(version==='v65'){assert.equal(z.hist.T01.lastSel,selected);assert.equal(z.hist.G23.lastSel,selected);}
}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v66.js')>assets.indexOf('qbank_source_audit_v65.js'));assert.ok(read('qbank_patch_v5.js').includes('qbank_source_audit_v66.js'));
console.log(JSON.stringify({result:'PASS',questions:q.length,changed:rev.changed.length,choices:rev.changed.length*5,distribution:counts,migrationCases:25,offlineAssets:assets.length}));
