const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with79){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with79&&f==='qbank_source_audit_v79.js'))continue;if(f==='qbank_source_audit_v80.js')continue;if(f==='qbank_source_audit_v81.js')continue;if(f==='qbank_source_audit_v82.js')continue;if(f==='qbank_source_audit_v83.js')continue;if(f==='qbank_source_audit_v84.js')continue;if(f==='qbank_source_audit_v85.js')continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_source_audit_v89.js')continue;if(f==='qbank_source_audit_v90.js')continue;if(f==='qbank_source_audit_v91.js')continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V79,ids=['W30','W31','W32','W34','W35'],stale=[];
assert.equal(before.QBANK.length,194);assert.equal(q.length,194);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(review.stale),stale);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.map(x=>x.id)));
assert.deepEqual(plain(after.WATER1_ARCHIVED_QUESTIONS.map(x=>x.id)),['L30','T17','W29','L01','W06','W25']);
let changed=0;for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);if(ids.includes(x.id)){changed++;assert.equal(x.a,old.a,x.id);assert.deepEqual(plain(x.v),plain(old.v),x.id);assert.equal(x.o.length,5);assert.equal(x.e.length,5);assert.equal(x.contentReviewVersion,'v79');assert.match(x.src,/US EPA|環境省|WHO|ATSDR|USGS|NCI/);if(!stale.includes(x.id)){assert.equal(x.q,old.q);assert.deepEqual(plain(x.o),plain(old.o));assert.deepEqual(plain(x.e),plain(old.e));assert.equal(x.p,old.p);}else assert.ok(x.p.length>=old.p.length/2);}else assert.deepEqual(plain(x),plain(old),x.id);}assert.equal(changed,5);
const counts=[0,0,0,0,0];for(const x of q){assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);counts[x.a]++;}assert.deepEqual(counts,[38,38,40,40,38]);
for(const version of ['v61','v77','v78'])for(const id of ids)for(let sel=0;sel<5;sel++){
 const state={bankContentVersion:version,hist:{[id]:{attempts:4,lastSel:sel,dueAt:1900000000000}},total:99,current:id,currentSel:sel,currentAnswered:true};const original=JSON.stringify(state),z=review.migrate(state);assert.equal(JSON.stringify(state),original);assert.equal(z.bankContentVersion,'v79');assert.equal(z.currentSel,sel);assert.equal(z.currentAnswered,true);assert.equal(z.hist[id].lastSel,sel);assert.equal(z.hist[id].attempts,4);assert.deepEqual(plain(review.migrate(z)),plain(z));
}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v79.js')>assets.indexOf('qbank_source_audit_v78.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v99'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:6,reviewed:5,choices:25,distribution:counts,migrationCases:75,offlineAssets:assets.length}));
