const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with95){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with95&&f==='qbank_source_audit_v95.js'))continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V95,ids=['H38','L36','L37','G38','G39','H39'],retired=['H40','L38'];
assert.equal(before.QBANK.length,187);assert.equal(q.length,185);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(review.retired),retired);assert.deepEqual(plain(review.stale),[]);
assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.filter(x=>!retired.includes(x.id)).map(x=>x.id)));
const archive=after.WATER1_ARCHIVED_QUESTIONS;assert.deepEqual(plain(archive.map(x=>x.id)),['L30','T17','W29','L01','W06','W25','L04','L10','L06','H20','L27','H29','L32','H40','L38']);assert.equal(new Set([...q,...archive].map(x=>x.id)).size,200);
for(const id of retired){const z=archive.find(x=>x.id===id);assert.deepEqual(plain(z.coverageTrim.coveredBy),plain(review.coveredBy[id]));for(const cover of z.coverageTrim.coveredBy)assert.ok(q.some(x=>x.id===cover));}
for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);assert.ok(x.e.every(s=>typeof s==='string'&&s.length>0),x.id);assert.ok(x.a>=0&&x.a<5,x.id);assert.ok(/^v(?:6[3-9]|[7-9]\d)$/.test(x.contentReviewVersion),x.id);assert.match(x.src,/https:\/\//,x.id);if(ids.includes(x.id)){for(const key of ['a','q','v','o','p'])assert.deepEqual(plain(x[key]),plain(old[key]),x.id+':'+key);assert.deepEqual(plain(x.e),plain(x.id==='G38'?old.e.map(s=>s.replace('最新公表の令和5年度実績','令和5年度実績')):old.e),x.id+':e');assert.equal(x.contentReviewVersion,'v95');assert.match(x.src,/US EPA|USGS|環境省/);}else assert.deepEqual(plain(x),plain(old),x.id);}
const counts=[0,0,0,0,0];for(const x of q)counts[x.a]++;assert.deepEqual(counts,[36,36,40,36,37]);
let cases=0;for(const version of ['v61','v92','v93','v94'])for(const id of [...ids,...retired])for(let sel=0;sel<5;sel++){const state={bankContentVersion:version,hist:{[id]:{attempts:4,lastSel:sel,dueAt:1900000000000}},total:99,current:id,currentSel:sel,currentAnswered:true},original=JSON.stringify(state),baseline=before.WATER1_EXAM_PRACTICE_V61.migrate(state),z=review.migrate(state);assert.equal(JSON.stringify(state),original);assert.equal(z.bankContentVersion,'v95');assert.equal(z.current,retired.includes(id)?null:baseline.current);assert.equal(z.currentSel,retired.includes(id)?null:baseline.currentSel);assert.equal(z.currentAnswered,retired.includes(id)?false:baseline.currentAnswered);assert.equal(z.hist[id].lastSel,baseline.hist[id].lastSel);assert.equal(z.hist[id].attempts,baseline.hist[id].attempts);assert.deepEqual(plain(review.migrate(z)),plain(z));cases++;}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v95.js')>assets.indexOf('qbank_source_audit_v94.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v97'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archive.length,reviewed:q.length,choices:q.length*5,remaining:0,distribution:counts,migrationCases:cases,offlineAssets:assets.length}));
