const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function load(with85){const noop=()=>{},document={readyState:'loading',addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},dataset:{},setAttribute:noop,appendChild:noop}),head:{appendChild:noop}};const c={document,console,setTimeout:noop,setInterval:noop,addEventListener:noop};c.window=c;vm.createContext(c);for(const f of ['qbank_v3.js','qbank_extra_v4.js',...Array.from(read('qbank_patch_v5.js').matchAll(/src="\.\/([^"?]+)/g),m=>m[1])]){if(['ui_polish_v46.js','study_workflow_v57.js','compact_menu_v58.js'].includes(f)||(!with85&&f==='qbank_source_audit_v85.js'))continue;if(f==='qbank_source_audit_v86.js')continue;if(f==='qbank_source_audit_v87.js')continue;if(f==='qbank_source_audit_v88.js')continue;if(f==='qbank_source_audit_v89.js')continue;if(f==='qbank_source_audit_v90.js')continue;if(f==='qbank_source_audit_v91.js')continue;if(f==='qbank_source_audit_v92.js')continue;if(f==='qbank_source_audit_v93.js')continue;if(f==='qbank_source_audit_v94.js')continue;if(f==='qbank_source_audit_v95.js')continue;if(f==='qbank_review_v63.js'||f==='qbank_review_v64.js')continue;if(f==='qbank_public_restore_v96.js')continue;vm.runInContext(read(f),c,{filename:f});}return c;}
const before=load(false),after=load(true),ids=['G07','H06','H09','G11','G12','G13'],q=after.QBANK,review=after.WATER1_SOURCE_AUDIT_V85,archived=after.WATER1_ARCHIVED_QUESTIONS;
assert.equal(before.QBANK.length,192);assert.equal(q.length,191);assert.deepEqual(plain(review.changed),ids);assert.deepEqual(plain(review.retired),['L06']);assert.deepEqual(plain(review.coveredBy),['W01','W36']);assert.deepEqual(plain(q.map(x=>x.id)),plain(before.QBANK.filter(x=>x.id!=='L06').map(x=>x.id)));
assert.deepEqual(plain(archived.map(x=>x.id)),['L30','T17','W29','L01','W06','W25','L04','L10','L06']);assert.equal(new Set([...q,...archived].map(x=>x.id)).size,200);
for(const x of q){const old=before.QBANK.find(y=>y.id===x.id);assert.equal(x.a,old.a,x.id);assert.equal(x.o.length,5,x.id);assert.equal(x.e.length,5,x.id);if(ids.includes(x.id)){assert.equal(x.q,old.q);assert.deepEqual(plain(x.v),plain(old.v));assert.deepEqual(plain(x.o),plain(old.o));assert.deepEqual(plain(x.e),plain(old.e));assert.equal(x.p,old.p);assert.equal(x.contentReviewVersion,'v85');assert.match(x.src,/US EPA|環境省|ISO|e-Gov/);}else assert.deepEqual(plain(x),plain(old),x.id);}
const old=before.QBANK.find(x=>x.id==='L06'),z=archived.at(-1);assert.equal(z.q,old.q);assert.deepEqual(plain(z.o),plain(old.o));assert.deepEqual(plain(z.e),plain(old.e));for(const id of z.coverageTrim.coveredBy)assert.ok(q.some(x=>x.id===id));assert.match(q.find(x=>x.id==='W01').q,/水温・DO/);assert.match(q.find(x=>x.id==='W36').q,/鉛直分布/);
const counts=[0,0,0,0,0];for(const x of q)counts[x.a]++;assert.deepEqual(counts,[38,37,40,39,37]);
for(const version of ['v61','v83','v84'])for(let sel=0;sel<5;sel++){const s={bankContentVersion:version,hist:{L06:{attempts:5,lastSel:sel,dueAt:1900000000000},G07:{lastSel:sel}},total:9,current:'L06',currentSel:sel,currentAnswered:true,other:{keep:1}},original=JSON.stringify(s),r=review.migrate(s);assert.equal(JSON.stringify(s),original);assert.equal(r.bankContentVersion,'v85');assert.equal(r.current,null);assert.equal(r.currentSel,null);assert.equal(r.currentAnswered,false);assert.equal(r.hist.L06.attempts,5);assert.equal(r.hist.L06.lastSel,sel);assert.equal(r.hist.L06.dueAt,1900000000000);assert.equal(r.hist.G07.lastSel,sel);assert.deepEqual(plain(r.other),s.other);assert.deepEqual(plain(review.migrate(r)),plain(r));}
for(const id of ids){const r=review.migrate({bankContentVersion:'v81',hist:{[id]:{lastSel:2}},current:id,currentSel:2,currentAnswered:true});assert.equal(r.current,id);assert.equal(r.currentSel,2);assert.equal(r.currentAnswered,true);assert.equal(r.hist[id].lastSel,2);}
const sw=read('sw.js'),assets=Array.from(sw.matchAll(/'\.\/([^']+)'/g),m=>m[1]);assert.deepEqual(assets.filter(f=>!fs.existsSync(path.join(root,f))),[]);assert.ok(assets.indexOf('qbank_source_audit_v85.js')>assets.indexOf('qbank_source_audit_v84.js'));assert.match(read('ui_polish_v46.js'),/RELEASE='v97'/);
console.log(JSON.stringify({result:'PASS',active:q.length,archived:archived.length,reviewed:6,choices:30,retired:['L06'],distribution:counts,migrationCases:21,offlineAssets:assets.length}));
