const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'standards-drill-data-v1.js'),'utf8'),ctx);
const G=ctx.window.STANDARDS_TABLES||[],html=fs.readFileSync(path.join(root,'standards-drill.html'),'utf8'),errs=[];const ok=(c,m)=>{if(!c)errs.push(m)};
ok(G.length===12,`table groups ${G.length}, expected 12`);const ids=new Set();for(const g of G){ok(!ids.has(g.id),`duplicate group ${g.id}`);ids.add(g.id);ok(Array.isArray(g.cols)&&g.cols.length>=2,`${g.id} columns`);ok(Array.isArray(g.rows)&&g.rows.length>0,`${g.id} rows`);for(const r of g.rows)ok(r.length===g.cols.length,`${g.id} row width`)}
const get=id=>G.find(g=>g.id===id),row=(id,name)=>{const g=get(id);return g&&g.rows.find(r=>r[0]===name)};
ok(row('water-health','カドミウム')[1]==='0.003 mg/L以下','water Cd');ok(row('water-health','六価クロム')[1]==='0.02 mg/L以下','water CrVI');ok(row('water-health','総水銀')[1]==='0.0005 mg/L以下','water Hg');ok(row('water-health','ふっ素')[1]==='0.8 mg/L以下','water F');ok(row('water-health','ほう素')[1]==='1 mg/L以下','water B');ok(row('water-health','1,4-ジオキサン')[1]==='0.05 mg/L以下','water dioxane');
ok(row('groundwater','クロロエチレン（塩化ビニルモノマー）')[1]==='0.002 mg/L以下','groundwater VC');ok(row('groundwater','1,2-ジクロロエチレン')[1]==='0.04 mg/L以下','groundwater 1,2-DCE');
ok(row('eff-harm','カドミウム及びその化合物')[1]==='0.03 mg Cd/L','eff Cd');ok(row('eff-harm','六価クロム化合物')[1]==='0.2 mg Cr(VI)/L','eff CrVI');ok(row('eff-harm','水銀及びアルキル水銀その他の水銀化合物')[1]==='0.005 mg Hg/L','eff Hg');ok(/10 \/ 海域 230/.test(row('eff-harm','ほう素及びその化合物')[1]),'eff B sea split');ok(/8 \/ 海域 15/.test(row('eff-harm','ふっ素及びその化合物')[1]),'eff F sea split');ok(row('eff-harm','1,4-ジオキサン')[1]==='0.5 mg/L','eff dioxane');
ok(/160 mg\/L（日間平均120）/.test(row('eff-other','BOD')[1]),'BOD effluent');ok(/200 mg\/L（日間平均150）/.test(row('eff-other','SS')[1]),'SS effluent');ok(row('eff-other','大腸菌数')[1]==='日間平均 800 CFU/mL','E coli effluent');ok(/120 mg\/L（日間平均60）/.test(row('eff-other','窒素')[1]),'N effluent');ok(/16 mg\/L（日間平均8）/.test(row('eff-other','りん')[1]),'P effluent');
ok(get('river').rows.map(r=>r[2]).join('|')==='1 mg/L以下|2 mg/L以下|3 mg/L以下|5 mg/L以下|8 mg/L以下|10 mg/L以下','river BOD sequence');ok(get('lake').rows.map(r=>r[2]).join('|')==='1 mg/L以下|3 mg/L以下|5 mg/L以下|8 mg/L以下','lake COD sequence');ok(get('lake-np').rows.map(r=>r[1]).join('|')==='0.1 mg/L以下|0.2 mg/L以下|0.4 mg/L以下|0.6 mg/L以下|1 mg/L以下','lake TN sequence');ok(get('sea').rows.map(r=>r[2]).join('|')==='2 mg/L以下|3 mg/L以下|8 mg/L以下','sea COD sequence');ok(get('sea-np').rows.map(r=>r[2]).join('|')==='0.02 mg/L以下|0.03 mg/L以下|0.05 mg/L以下|0.09 mg/L以下','sea TP sequence');ok(get('bottom-do').rows.map(r=>r[1]).join('|')==='4.0 mg/L以上|3.0 mg/L以上|2.0 mg/L以上','bottom DO sequence');
ok(/0\.07 ppm/.test(row('air-env','光化学オキシダント（Ox）')[1])&&/0\.04 ppm/.test(row('air-env','光化学オキシダント（Ox）')[1]),'current Ox standard');ok(row('air-env','トリクロロエチレン')[1]==='年平均130 µg/m³以下','current air TCE 130');ok(!/トリクロロエチレン','年平均200 µg\/m³/.test(fs.readFileSync(path.join(root,'standards-drill-data-v1.js'),'utf8')),'old TCE 200 must not return');ok(/15 µg\/m³/.test(row('air-env','PM2.5')[1])&&/35 µg\/m³/.test(row('air-env','PM2.5')[1]),'PM2.5 values');
ok(row('air-emission','SOx許容排出量の式')[1]==='q＝K×10⁻³×He²','SOx formula');ok(row('air-emission','SOx 一般排出基準のK値')[1]==='3.0～17.5','SOx general K');ok(row('air-emission','SOx 特別排出基準のK値')[1]==='1.17～2.34','SOx special K');ok(row('air-emission','ばいじん 一般排出基準')[1]==='0.04～0.5 g/Nm³','dust general');
ok(/water1_standards_drill_v1/.test(html),'separate localStorage key');ok(!/water1_bank_v3/.test(html),'must not touch 200-question history key');ok(/standards-drill-data-v1\.js\?v=2/.test(html),'data loader');ok(/slice\(0,2\)/.test(html)&&/shuffled\(\[ans,\.\.\.p\]\)/.test(html),'three-choice builder');ok(/次の空欄へ/.test(html),'next action');ok(/苦手セルを優先/.test(html),'weak-priority action');ok(/一覧学習/.test(html),'study mode');
let quizCells=0;for(const g of G)for(const r of g.rows)g.cols.forEach((c,i)=>{if(c[2]&&String(r[i])!=='—')quizCells++});ok(quizCells>=150,`quiz cells ${quizCells}, expected >=150`);
console.log('STANDARDS_GROUPS',G.length,'QUIZ_CELLS',quizCells,'LOCALSTORAGE','water1_standards_drill_v1');if(errs.length){console.error('FAIL standards drill audit\n'+errs.join('\n'));process.exit(1)}console.log('PASS standards drill current-value/UI audit');