const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const scripts=[
'qbank_v3.js','qbank_extra_v4.js','qbank_core_patch_v7.js','qbank_detail_patch_v6.js','qbank_enrichment_v7.js','qbank_detail_round1_v7.js','qbank_detail_complete_v7.js',
'qbank_gap_batch1_v7.js','qbank_gap_batch2_v7.js','qbank_gap_batch3_v7.js','qbank_gap_batch4_v7.js','qbank_gap_batch4_fix_v7.js','qbank_gap_batch5_v7.js','qbank_gap_batch6_v7.js','qbank_gap_batch6_fix_v7.js','qbank_gap_batch7_v7.js','qbank_gap_batch8_v7.js','qbank_gap_batch9_v7.js','qbank_gap_batch10_v7.js','qbank_gap_batch11_v7.js','qbank_gap_batch12_v7.js',
'qbank_detail_quality_fix_v23.js','qbank_undefined_fix_v7.js','qbank_exam_quality_patch_v34.js','qbank_visual_fix_v35.js','qbank_unit_typography_v1.js','qbank_content_restructure_v39.js','qbank_distractor_plausibility_v40.js','qbank_semantic_rewrite_gw_v42.js','qbank_semantic_rewrite_th_v42.js','qbank_semantic_rewrite_l_v42.js','qbank_semantic_strengthen_g_v42.js','qbank_semantic_strengthen_w_v42.js','qbank_semantic_strengthen_t_v42.js','qbank_semantic_strengthen_h_v42.js','qbank_semantic_strengthen_l_v42.js','qbank_semantic_polish_v43.js','qbank_semantic_polish_v44.js','qbank_semantic_polish_v45.js','qbank_exam_difficulty_stage1_v47.js','qbank_recent_exam_upgrade_v47.js','qbank_recent_exam_audit_finalize_v47.js','qbank_exam_difficulty_stage2_v48.js','qbank_exam_difficulty_stage3_v49.js','qbank_exam_difficulty_stage3_fix_v49.js','qbank_exam_difficulty_stage4_v50.js','qbank_exam_difficulty_stage5_v51.js','qbank_learning_visuals_v52.js','visual_aid_audit_v53.js','qbank_learning_visuals_v53.js','qbank_learning_visuals_v53_mobilefix.js'
];
const noop=()=>{};const document={readyState:'complete',addEventListener:noop,getElementById:()=>null,querySelectorAll:()=>[],body:{},head:{appendChild:noop},createElement:()=>({})};
const localStorage={getItem:()=>null,setItem:noop,removeItem:noop};
const ctx={window:{QBANK:[]},document,console,setTimeout:(f)=>{try{f()}catch(e){}},clearTimeout:noop,MutationObserver:function(){this.observe=noop},localStorage,Set,Map,Math,JSON,Number,String,Array,Object,RegExp,Date};ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.localStorage=localStorage;vm.createContext(ctx);
for(const f of scripts){const p=path.join(root,f);if(!fs.existsSync(p))throw new Error('missing '+f);vm.runInContext(fs.readFileSync(p,'utf8'),ctx,{filename:f});}
const bank=ctx.window.QBANK||[],arc=ctx.window.WATER1_ARCHIVED_QUESTIONS||[],meta=ctx.window.WATER1_VISUAL_AID_AUDIT||{},release=ctx.window.WATER1_VISUAL_AID_RELEASE||{},mobileFix=ctx.window.WATER1_VISUAL_AID_MOBILE_FIX||{},cfg=JSON.parse(fs.readFileSync(path.join(root,'visual_aid_audit_v53.json'),'utf8')),errs=[];const ok=(c,m)=>{if(!c)errs.push(m)};
function uniq(a){return new Set(a).size===a.length;}
const activeIds=bank.map(x=>x.id),activeSet=new Set(activeIds),allCfg=cfg.allActiveIds||[],hi=cfg.highPriority||[],med=cfg.mediumPriority||[],none=cfg.none||[],union=hi.concat(med,none);
ok(bank.length===199,`active bank ${bank.length}`);ok(arc.length===1&&arc[0].id==='L30','archive invariant');ok(allCfg.length===199&&uniq(allCfg),'config allActiveIds must contain 199 unique IDs');ok(union.length===199&&uniq(union),'HIGH/MEDIUM/NONE must partition 199 IDs exactly once');ok(allCfg.every(id=>activeSet.has(id))&&activeIds.every(id=>allCfg.includes(id)),'config IDs must exactly match active bank');ok(!allCfg.includes('L30')&&!union.includes('L30'),'archived L30 must not be in active visual audit');ok(hi.length===64&&med.length===60&&none.length===75,`classification counts ${hi.length}/${med.length}/${none.length}`);
ok(meta.version==='v53'&&Array.isArray(meta.rows)&&meta.rows.length===199,'runtime v53 audit rows missing');ok(meta.counts&&meta.counts.active===199&&meta.counts.high===64&&meta.counts.medium===60&&meta.counts.none===75,'runtime count mismatch');ok(release.version==='v53'&&release.high===64&&release.medium===60&&release.none===75,'visual release metadata mismatch');ok(mobileFix.version==='v53.1','mobile visual-width fix metadata missing');
for(const x of bank){const r=meta.rows.find(z=>z.id===x.id);ok(!!r,`${x.id} runtime audit row missing`);if(!r)continue;ok(['high','medium','none'].includes(x.visualAidPriority),`${x.id} invalid priority`);ok(typeof x.visualAidReason==='string'&&x.visualAidReason.length>20,`${x.id} reason missing`);if(r.priority==='high'){ok(x.visualAidCandidate===true,`${x.id} high candidate false`);ok(['v53-high','v52-existing'].includes(x.visualAidRendered),`${x.id} high visual not rendered`);ok(String(x.p).includes(`data-v53-aid="${x.id}"`)||String(x.p).includes(`data-flow-id="${x.id}"`),`${x.id} high markup missing`);if(x.visualAidRendered==='v53-high')ok(!String(x.p).includes(`<details class="water1-aid-medium" data-v53-aid="${x.id}"`),`${x.id} high visual must not be collapsed`);}else if(r.priority==='medium'){ok(x.visualAidCandidate===true,`${x.id} medium candidate false`);ok(x.visualAidRendered==='v53-medium',`${x.id} medium visual not rendered`);ok(String(x.p).includes(`<details class="water1-aid-medium" data-v53-aid="${x.id}"`),`${x.id} medium details missing`);ok(String(x.p).includes('判断マップ'),`${x.id} medium judgment map missing`);}else{ok(x.visualAidCandidate===false,`${x.id} none candidate true`);ok(x.visualAidRendered==='none',`${x.id} none render marker`);ok(!String(x.p).includes(`data-v53-aid="${x.id}"`),`${x.id} none unexpectedly got v53 aid`);}}
const mustHigh={W03:['富栄養化','内部負荷'],T30:['不連続点','遊離残留塩素'],H18:['TCE','排ガス処理'],L12:['製油所','SWS'],L38:['めっき','Cr(VI)']};
for(const [id,words] of Object.entries(mustHigh)){const x=bank.find(q=>q.id===id);ok(x,`${id} missing`);if(x)for(const w of words)ok(String(x.p).includes(w),`${id} high content missing ${w}`);}
for(const id of ['T04','H04','H07','H10','T21','T22','L33']){const x=bank.find(q=>q.id===id);ok(x&&x.visualAidPriority==='high',`${id} v52 carryover must remain HIGH`);ok(x&&x.visualAidRendered==='v52-existing',`${id} v52 flow duplicated/replaced`);}
for(const id of ['T10','H31','L24']){const x=bank.find(q=>q.id===id);ok(x&&x.visualAidPriority==='medium',`${id} medium classification`);ok(x&&String(x.p).includes('water1-aid-medium'),`${id} medium UI missing`);}
const loader=fs.readFileSync(path.join(root,'qbank_patch_v5.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),ui=fs.readFileSync(path.join(root,'ui_polish_v46.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),fix=fs.readFileSync(path.join(root,'qbank_learning_visuals_v53_mobilefix.js'),'utf8');
const p52=loader.indexOf('qbank_learning_visuals_v52.js?v=149'),pa=loader.indexOf('visual_aid_audit_v53.js?v=150'),pv=loader.indexOf('qbank_learning_visuals_v53.js?v=150'),pf=loader.indexOf('qbank_learning_visuals_v53_mobilefix.js?v=151'),pu=loader.indexOf('ui_polish_v46.js?v=150');ok(p52>=0&&p52<pa&&pa<pv&&pv<pf&&pf<pu,'v53 loader order');ok(sw.includes("'./visual_aid_audit_v53.js'")&&sw.includes("'./qbank_learning_visuals_v53.js'")&&sw.includes("'./qbank_learning_visuals_v53_mobilefix.js'")&&sw.includes("'./visual_aid_audit_v53.json'"),'service worker v53 assets');ok(sw.includes('visual-aid-v53-mobilefix'),'service worker v53 mobile-fix marker');ok(fix.includes('.water1-flow{width:100%;max-width:100%;min-width:0;box-sizing:border-box'),'flow mobile width guard missing');ok(fix.includes('.water1-flow-list,.water1-flow-step,.water1-flow-branches,.water1-flow-branch'),'flow child width guard missing');ok(ui.includes("var RELEASE='v53'"),'UI release v53 missing');ok(index.includes("var KEY='water1_bank_v3'"),'learning-history key changed');
console.log('VISUAL_AID_V53 ACTIVE',bank.length,'HIGH',hi.length,'MEDIUM',med.length,'NONE',none.length,'ARCHIVED',arc.map(x=>x.id).join(','),'MOBILE_FIX',mobileFix.version);if(errs.length){console.error('FAIL v53 all-question visual-aid audit\n'+errs.join('\n'));process.exit(1)}console.log('PASS v53 all-question visual-aid classification, rendering and mobile-width audit');
